name: workflow

on:
  push:
    branches:
      - main
      paths-ignore:
        - 'README.md'

job:
  integration:
    name: Continuous integration
    run-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"